# Generated by Django 2.0.1 on 2019-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capitallx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_source', models.CharField(default='', max_length=30, verbose_name='资金方')),
                ('l_amount', models.CharField(default='', max_length=1000, verbose_name='资金')),
            ],
            options={
                'verbose_name': '资金配置',
                'verbose_name_plural': '资金配置',
            },
        ),
        migrations.CreateModel(
            name='Data_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=30, verbose_name='用例')),
                ('casecno', models.CharField(max_length=50, verbose_name='合同号')),
                ('dbname', models.CharField(max_length=30, verbose_name='数据库')),
                ('sqlval', models.CharField(max_length=1000, verbose_name='sql语句')),
                ('checkone', models.CharField(default='', max_length=30, verbose_name='对比字段')),
                ('checkmath', models.CharField(default='', max_length=30, verbose_name='公式')),
                ('checktwo', models.CharField(default='', max_length=30, verbose_name='参照字段')),
                ('markone', models.CharField(max_length=300, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '数据对比',
                'verbose_name_plural': '数据对比',
            },
        ),
        migrations.CreateModel(
            name='Detail_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=30, verbose_name='模块')),
                ('runmark', models.CharField(max_length=100, null=True, verbose_name='运行源')),
                ('casename', models.CharField(max_length=30, verbose_name='用例')),
                ('valone', models.CharField(default='', max_length=30, verbose_name='对比值')),
                ('valtwo', models.CharField(default='', max_length=30, verbose_name='参照值')),
                ('status', models.CharField(max_length=300, null=True, verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='用户名')),
                ('casecno', models.CharField(max_length=50, verbose_name='合同号')),
                ('checkmath', models.CharField(default='', max_length=30, verbose_name='公式')),
            ],
            options={
                'verbose_name': '对比结果',
                'verbose_name_plural': '对比结果',
            },
        ),
        migrations.CreateModel(
            name='Detaildata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=30, verbose_name='模块')),
                ('caseall', models.CharField(max_length=200, verbose_name='自动化用例数')),
                ('caserun', models.CharField(max_length=200, verbose_name='已执行用例数')),
                ('cpass', models.CharField(max_length=30, verbose_name='通过数')),
                ('cfail', models.CharField(default='', max_length=30, verbose_name='失败数')),
                ('runrate', models.CharField(default='', max_length=30, verbose_name='执行覆盖率')),
                ('passrate', models.CharField(default='', max_length=30, verbose_name='执行通过率')),
                ('runnum', models.CharField(max_length=100, null=True, verbose_name='脚本执行次数')),
                ('runmark', models.CharField(max_length=100, null=True, verbose_name='执行标记')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '详细数据',
                'verbose_name_plural': '详细数据',
            },
        ),
        migrations.CreateModel(
            name='Evnccdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systpye', models.CharField(choices=[('即有宝', '即有宝'), ('即有钱包', '即有钱包'), ('现金贷', '现金贷'), ('后台对内', '后台对内'), ('产品管理平台', '产品管理平台'), ('中移金服', '中移金服'), ('数据库', '数据库'), ('其他', '其他')], default='即有宝', max_length=300, null=True, verbose_name='系统类别')),
                ('evntpye', models.CharField(choices=[('测试环境', '测试环境'), ('准生产', '准生产'), ('正式环境', '正式环境'), ('其他', '其他')], default='测试环境', max_length=300, null=True, verbose_name='环境类别')),
                ('evn_name', models.CharField(max_length=300, verbose_name='系统名称')),
                ('evn_address', models.CharField(max_length=300, verbose_name='系统地址')),
                ('evn_account', models.CharField(max_length=300, verbose_name='账号密码')),
            ],
            options={
                'verbose_name': '环境信息',
                'verbose_name_plural': '环境信息',
            },
        ),
        migrations.CreateModel(
            name='Mobiledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=30, verbose_name='合同号')),
                ('con_name', models.CharField(max_length=20, verbose_name='合同名称')),
                ('con_ident', models.CharField(max_length=30, verbose_name='身份证')),
                ('con_phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('capital_source', models.CharField(default='', max_length=30, verbose_name='资金方')),
                ('con_status', models.CharField(default='', max_length=30, verbose_name='合同状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('username', models.CharField(max_length=300, null=True, verbose_name='运行人')),
                ('runnum', models.CharField(max_length=300, null=True, verbose_name='标记值')),
                ('case_no', models.CharField(max_length=300, null=True, verbose_name='用例编号')),
            ],
            options={
                'verbose_name': '合同查询',
                'verbose_name_plural': '合同查询',
            },
        ),
        migrations.CreateModel(
            name='Mobiletest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conname', models.CharField(max_length=6, verbose_name='合同名称')),
                ('connum', models.IntegerField(verbose_name='生成数量')),
                ('pcname', models.CharField(choices=[('android真机：小米6.0.1MX', 'android真机：小米6.0.1MX'), ('android模拟器', 'android模拟器'), ('android真机：华为P10', 'android真机：华为P10'), ('android真机：MEIZU PRO6', 'android真机：MEIZU PRO6'), ('android真机：小米8.0.0', 'android真机：小米8.0.0'), ('android真机：小米8.0.0MI6', 'android真机：小米8.0.0MI6')], default='android真机：小米6.0.1MX', max_length=40, null=True, verbose_name='类型')),
                ('pcip', models.GenericIPAddressField(choices=[('127.0.0.1', '127.0.0.1'), ('10.14.21.20', '10.14.21.20'), ('10.14.21.118', '10.14.21.118'), ('10.14.21.33', '10.14.21.33'), ('10.14.21.98', '10.14.21.98'), ('10.14.21.125', '10.14.21.125')], default='127.0.0.1', verbose_name='服务')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('runstatus', models.CharField(default='未运行', max_length=100, verbose_name='运行状态')),
                ('runnum', models.IntegerField(default=1, editable=False, verbose_name='运行次数')),
            ],
            options={
                'verbose_name': '即有宝订单',
                'verbose_name_plural': '即有宝订单',
            },
        ),
        migrations.CreateModel(
            name='Paramdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, null=True, verbose_name='用户名')),
                ('param_one', models.CharField(max_length=300, null=True, verbose_name='门店ID')),
                ('param_two', models.CharField(max_length=300, null=True, verbose_name='商品类型')),
                ('param_three', models.CharField(max_length=300, null=True, verbose_name='产品版本')),
                ('param_four', models.CharField(max_length=300, null=True, verbose_name='商品总额')),
                ('param_five', models.CharField(max_length=300, null=True, verbose_name='首付总额')),
                ('param_six', models.CharField(max_length=300, null=True, verbose_name='保险一')),
                ('param_seven', models.CharField(max_length=300, null=True, verbose_name='贷款期数')),
                ('param_eight', models.CharField(max_length=300, null=True, verbose_name='商品小类')),
                ('param_nine', models.CharField(max_length=300, null=True, verbose_name='商品品牌')),
                ('param_ten', models.CharField(max_length=300, null=True, verbose_name='保险二')),
                ('param_eleven', models.CharField(max_length=300, null=True, verbose_name='资金方')),
                ('param_twelve', models.CharField(max_length=300, null=True, verbose_name='合同状态')),
                ('case_no', models.CharField(max_length=300, null=True, verbose_name='编号')),
            ],
            options={
                'verbose_name': '参数配置',
                'verbose_name_plural': '参数配置',
            },
        ),
    ]
