# Generated by Django 2.0.1 on 2019-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiletest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletest',
            name='pcname',
            field=models.CharField(choices=[('android真机：小米6.0.1MX', 'android真机：小米6.0.1MX'), ('android模拟器', 'android模拟器'), ('android真机：华为P10', 'android真机：华为P10'), ('android真机：Honor Note10', 'android真机：Honor Note10'), ('android真机：MEIZU PRO6', 'android真机：MEIZU PRO6'), ('android真机：小米8.0.0', 'android真机：小米8.0.0'), ('android真机：小米8.0.0MI6', 'android真机：小米8.0.0MI6')], default='android真机：小米6.0.1MX', max_length=40, null=True, verbose_name='类型'),
        ),
    ]
