# Generated by Django 2.0.1 on 2019-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiletest', '0002_auto_20190111_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletest',
            name='cashnum',
            field=models.IntegerField(default=1, editable=False, verbose_name='运行次数'),
        ),
        migrations.AddField(
            model_name='mobiletest',
            name='livenum',
            field=models.IntegerField(default=1, editable=False, verbose_name='运行次数'),
        ),
    ]
