# Generated by Django 2.0.1 on 2019-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiletest', '0003_auto_20190117_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletest',
            name='cstatus',
            field=models.CharField(default='未运行', max_length=100, verbose_name='运行状态'),
        ),
        migrations.AddField(
            model_name='mobiletest',
            name='lstatus',
            field=models.CharField(default='未运行', max_length=100, verbose_name='运行状态'),
        ),
    ]
